### ISSUE TITLE
make error on macos 11.6

### ISSUE THREAD

**Issue by januszoles** [csstidy-c/csstidy#7] opened 2022-01-26 14:53 UTC
```
make
mkdir -p release/csstidy
c++ -o release/csstidy/background.o -c -O2 -fomit-frame-pointer  csstidy/background.cpp
c++ -o release/csstidy/conversions.o -c -O2 -fomit-frame-pointer  csstidy/conversions.cpp
c++ -o release/csstidy/cssopt.o -c -O2 -fomit-frame-pointer  csstidy/cssopt.cpp
csstidy/cssopt.cpp:177:56: warning: implicit conversion from 'int' to 'std::basic_string<char>::value_type' (aka 'char') changes value from 255 to -1 [-Wconstant-conversion]
                        if(atoi(color_tmp[i].c_str()) > 255) color_tmp[i] = 255;
                                                                          ~ ^~~
1 warning generated.
c++ -o release/csstidy/csspp_globals.o -c -O2 -fomit-frame-pointer  csstidy/csspp_globals.cpp
c++ -o release/csstidy/misc.o -c -O2 -fomit-frame-pointer  csstidy/misc.cpp
c++ -o release/csstidy/csstidy.o -c -O2 -fomit-frame-pointer  csstidy/csstidy.cpp
In file included from csstidy/csstidy.cpp:20:
In file included from csstidy/csspp_globals.hpp:34:
csstidy/umap.hpp:125:3: warning: non-void function does not return a value in all control paths [-Wreturn-type]
                }
                ^
csstidy/csstidy.cpp:82:42: note: in instantiation of member function 'umap<std::string, std::string>::at' requested here
                string property = css[media][selector].at(k);
                                                       ^
1 warning generated.
c++ -o release/csstidy/file_functions.o -c -O2 -fomit-frame-pointer  csstidy/file_functions.cpp
c++ -o release/csstidy/umap.o -c -O2 -fomit-frame-pointer  csstidy/umap.cpp
c++ -o release/csstidy/main.o -c -O2 -fomit-frame-pointer  csstidy/main.cpp
csstidy/main.cpp:20:17: warning: using directive refers to implicitly-defined namespace 'std'
using namespace std;
                ^
1 warning generated.
c++ -o release/csstidy/prepare.o -c -O2 -fomit-frame-pointer  csstidy/prepare.cpp
c++ -o release/csstidy/parse_css.o -c -O2 -fomit-frame-pointer  csstidy/parse_css.cpp
c++ -o release/csstidy/trim.o -c -O2 -fomit-frame-pointer  csstidy/trim.cpp
c++ -o release/csstidy/print_css.o -c -O2 -fomit-frame-pointer  csstidy/print_css.cpp
csstidy/print_css.cpp:76:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
1 warning generated.
c++ -o release/csstidy/important.o -c -O2 -fomit-frame-pointer  csstidy/important.cpp
cd release; c++ -O2 -fomit-frame-pointer  -Wl,-z,noexecstack -o csstidy/csstidy csstidy/background.o csstidy/conversions.o csstidy/cssopt.o csstidy/csspp_globals.o csstidy/misc.o csstidy/csstidy.o csstidy/file_functions.o csstidy/umap.o csstidy/main.o csstidy/prepare.o csstidy/parse_css.o csstidy/trim.o csstidy/print_css.o csstidy/important.o
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [csstidy] Error 1
```

**Comment by tx-pandoc** [comment] 2022-01-26 15:13
Ouch... very old code style, indeed. And not compatible to clang. Will check if my macOS can reproduce the same issues and then fix.

**Comment by kevinhendricks** [comment] 2022-01-26 15:14
FWIW, first part looks a bit like mixing signed and unsigned char definitions which rolls 255 into -1 going from unsigned to signed.  I typically add -funsigned-char to the cppflags when building apps on macOS when I run into this as this is compiler and platform dependent.  Worth a shot.

And macOS clang always marks the stack as non-executable according to its docs so you should be able to remove the -Wl, -z, noexecstack since it is implicit.

**Comment by csstidy-c** [comment] 2022-01-26 15:21
Sure, this is on macOS. But the basic issue is that options are old and are from old gcc-only era. ;-)

**Comment by csstidy-c** [comment] 2022-09-05 17:04
fixed in develop branch

**Closed as completed by csstidy-c** 2022-09-05 17:04 UTC
